services:
  db:
    image: postgis/postgis:16-3.4
    container_name: farmassist-db
    restart: always
    environment:
      POSTGRES_DB: farmassist
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: farmassist-adminer
    restart: always
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    container_name: cinephiles-redis
    ports:
      - "6379:6379"
    # Optional: Saves data to disk every 60 seconds if at least 1 key changed
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: