# Generated by Django 6.0 on 2026-05-07 18:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_farm_pestreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='crop_type',
        ),
        migrations.CreateModel(
            name='FarmSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('planted_date', models.DateField(auto_now_add=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='PestDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_name', models.CharField(max_length=255)),
                ('severity_level', models.IntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('detection_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='api.farmseason')),
            ],
        ),
        migrations.CreateModel(
            name='PestAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to='api.farm')),
                ('source_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_alerts', to='api.pestdetection')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='api.pestdetection')),
            ],
        ),
        migrations.DeleteModel(
            name='PestReport',
        ),
    ]
