# Generated by Django 6.0 on 2026-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_farm_crop_type_farmseason_pestdetection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestdetection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pest_scans/'),
        ),
    ]
