# Generated by Django 6.0 on 2026-05-22 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pestdetection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='boundaries',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pestdetection',
            name='detection_location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
