# Generated by Django 6.0 on 2026-05-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_farm_boundaries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PestAlertBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_risk_score', models.FloatField()),
                ('notified_users', models.JSONField(default=list)),
                ('dismissed_by', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='api.pestdetection')),
            ],
        ),
        migrations.DeleteModel(
            name='PestAlert',
        ),
    ]
