# Generated by Django 6.0 on 2026-05-26 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pestalertbroadcast_delete_pestalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_hi', models.TextField(blank=True, null=True)),
                ('content_mr', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Crops', 'Crops'), ('Schemes', 'Schemes'), ('Market', 'Market'), ('Weather', 'Weather')], default='Crops', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
    ]
