# Generated by Django 6.0 on 2026-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_post_delete_communitypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestdetection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
